<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\vesafe_structure\VsForm;
use Drupal\vesafe_structure\VsField;

/**
 * Implements hook_form_alter().
 */
function vesafe_structure_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(VsForm::class)
    ->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function vesafe_structure_preprocess_field(&$variables) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(VsField::class)
    ->preprocessField($variables);
}
