<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\oira_masquerade\OmForm;

/**
 * Implements hook_form_alter().
 */
function oira_masquerade_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  Drupal::classResolver()
    ->getInstanceFromDefinition(OmForm::class)
    ->formAlter($form, $form_state, $form_id);
}

/*
 * @see \hook_local_tasks_alter()
 */

/**
 * Implements hook_local_tasks_alter().
 */
function oira_masquerade_local_tasks_alter(&$local_tasks)
{
  unset($local_tasks['content_moderation.moderated_content']);
}
