<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\ncw_backend\Form\NewsletterSubscriptionForm;
use Drupal\ncw_backend\ncwViewQA;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;


/**
 * Implements hook_views_query_alter().
 * @param ViewExecutable $view
 * @param QueryPluginBase $query
 * @return mixed
 */
function ncw_backend_views_query_alter(ViewExecutable $view, QueryPluginBase $query)
{
    return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ncwViewQA::class)
    -> viewsQueryAlter( $view, $query);
}


function ncw_backend_page_attachments(array &$attachments) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $attachments['#attached']['library'][] = 'ncw_backend/ncw_backend';
    return;
  }

}

/**
 * Implements hook_entity_extra_field_info().
 */
function ncw_backend_entity_extra_field_info() {
  $extra = [];

  // Creates a pseudo-field to show custom form for newsletter subscription.
  $extra['block_content']['newsletter_subscription_block']['display']['subscription_form'] = [
    'label' => t('Subscription form'),
    'description' => t('Subscription form pseudo field'),
    'weight' => 100,
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ncw_backend_block_content_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('subscription_form')) {
    $build['subscription_form'] = Drupal::formBuilder()->getForm(NewsletterSubscriptionForm::class);
  }
}

