<?php

use Drupal\napo_content_cart\NccView;

/**
 * Implements hook_theme().
 */
function napo_content_cart_theme($existing, $type, $theme, $path) {
  return [
    'ncc_element_modal' => [
      'variables' => [
        'elements' => NULL,
        'message' => NULL,
        'button' => NULL,
      ],
    ],
    'ncc_element_download' => [
      'variables' => [
        'image' => NULL,
        'title' => NULL,
        'description' => NULL,
        'url' => NULL,
        'file' => NULL,
        'remove' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_data_alter().
 */
function napo_content_cart_views_data_alter(array &$data) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(NccView::class)
    ->viewsDataAlter($data);
}
