<?php

use Drupal\Core\TempStore\PrivateTempStore;

/**
 * Implements HOOK_HELP().
 */
function content_cart_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.content_cart':
      return '<p> Este módulo almacena en una libreria temporal <strong>PrivateTempStore</strong>
los Napo_videos para poder descargarlos desde un carrito.</p><p>Se precisa poner un link/boton en el twig del tipo de contenido
para poder añadir a la cesta.  El enlace es:</p>
<p>Para añadir al carro: /content_cart/add/{node.id}</p>
<p>Parar descargar directamente: /content_cart/download/{node.id}</p>
';

  }
}
